export const INITIAL_USER_DETAILS = {
  id: "",
  email: "",
  fullName: "",
  birthday: "",
  isDoctor: false,
  doctorId: "",
  doctorName: "",
};


export const SYMPTOMS = [
  { index: 0, value: "fatigue", label: "Fatigue" },
  { index: 1, value: "vomiting", label: "Vomiting" },
  { index: 2, value: "high_fever", label: "High Fever" },
  { index: 3, value: "loss_of_appetite", label: "Loss of Appetite" },
  { index: 4, value: "nausea", label: "Nausea" },
  { index: 5, value: "headache", label: "Headache" },
  { index: 6, value: "abdominal_pain", label: "Abdominal Pain" },
  { index: 7, value: "yellowish_skin", label: "Yellowish Skin" },
  { index: 8, value: "yellowing_of_eyes", label: "Yellowing of Eyes" },
  { index: 9, value: "chills", label: "Chills" },
  { index: 10, value: "skin_rash", label: "Skin Rash" },
  { index: 11, value: "malaise", label: "Malaise" },
  { index: 12, value: "chest_pain", label: "Chest Pain" },
  { index: 13, value: "joint_pain", label: "Joint Pain" },
  { index: 14, value: "itching", label: "Itching" },
  { index: 15, value: "sweating", label: "Sweating" },
  { index: 16, value: "dark_urine", label: "Dark Urine" },
  { index: 17, value: "cough", label: "Cough" },
  { index: 18, value: "diarrhoea", label: "Diarrhoea" },
  { index: 19, value: "irritability", label: "Irritability" }
];

export const DISEASES = [
  { index: 0, label: "Vertigo"},
  { index: 1, label: "AIDS"},
  { index: 2, label: "Acne"},
  { index: 3, label: "Alcoholic Hepatitis"},
  { index: 4, label: "Allergy"},
  { index: 5, label: "Arthritis"},
  { index: 6, label: "Bronchial Asthma"},
  { index: 7, label: "Cervical Spondylosis"},
  { index: 8, label: "Chicken Pox"},
  { index: 9, label: "Chronix Scholestasis"},
  { index: 10, label: "Common Cold"},
  { index: 11, label: "Dengue"},
  { index: 12, label: "Diabetes"},
  { index: 13, label: "Dimorphic Hemmorhoids"},
  { index: 14, label: "Drug Reaction"},
  { index: 15, label: "Fungal Infection"},
  { index: 16, label: "GERD"},
  { index: 17, label: "Gastroenteritis"},
  { index: 18, label: "Heart Attack"},
  { index: 19, label: "Hepatitis B"},
  { index: 20, label: "Hepatitis C"},
  { index: 21, label: "Hepatitis D"},
  { index: 22, label: "Hepatitis E"},
  { index: 23, label: "Hypertension"},
  { index: 24, label: "Hyperthyroidism"},
  { index: 25, label: "Hypoglycemia"},
  { index: 26, label: "Hypothyroidism"},
  { index: 27, label: "Impetigo"},
  { index: 28, label: "Jaundice"},
  { index: 29, label: "Malaria"},
  { index: 30, label: "Migraine"},
  { index: 31, label: "Osteoarthristis"},
  { index: 32, label: "Paralysis (brain hemorrhage)"},
  { index: 33, label: "Peptic Ulcer Disease"},
  { index: 34, label: "Pneumonia"},
  { index: 35, label: "Psoriasis"},
  { index: 36, label: "Tuberculosis"},
  { index: 37, label: "Typhoid"},
  { index: 38, label: "Urinary Tract Infection"},
  { index: 39, label: "Varicose Veins"},
  { index: 40, label: "Hepatitis A"},
];

export const AVAIL_TIMES = [
  '09:00-10:00',
  '10:00-11:00',
  '11:00-12:00',
  '12:00-13:00',
  '13:00-14:00',
  '14:00-15:00',
  '15:00-16:00',
  '16:00-17:00'
];